In [ ]:
# data.info(verbose=True)

In [1]:
import numpy as np 
import pandas as pd 

# Load the large-scale dataset
# Note: Ensure the file path is correct in your local environment
data = pd.read_csv('accepted_2007_to_2018Q4.csv', low_memory=False)
data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'accepted_2007_to_2018Q4.csv'

In [6]:
data = pd.read_csv('accepted_2007_to_2018Q4.csv')

C:\Users\Admin\AppData\Local\Temp\ipykernel_12264\2567533633.py:1: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('accepted_2007_to_2018Q4.csv')

In [7]:
data.head(5)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260639e+06,2.260668e+06,...,10917.0,10917.000000,10917.0,10917.000000,8651.000000,10917.000000,10917.000000,34246.000000,34246.000000,34246.000000
mean,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,3.068792e-01,6.985882e+02,...,3.0,155.045981,3.0,13.743886,454.798089,11636.883942,193.994321,5010.664267,47.780365,13.191322
std,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,8.672303e-01,3.301038e+01,...,0.0,129.040594,0.0,9.671178,375.385500,7625.988281,198.629496,3693.122590,7.311822,8.159980
min,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,0.000000e+00,6.750000e+02,...,3.0,59.440000,3.0,5.000000,175.230000,5627.000000,44.440000,2208.000000,45.000000,6.000000
50%,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,...,3.0,119.140000,3.0,15.000000,352.770000,10028.390000,133.160000,4146.110000,45.000000,14.000000
75%,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,0.000000e+00,7.150000e+02,...,3.0,213.260000,3.0,22.000000,620.175000,16151.890000,284.190000,6850.172500,50.000000,18.000000
max,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

In [6]:
data.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=151)

In [7]:
drop_dt = ['member_id', 'url', 'desc', 'emp_title', 'zip_code', 'title']

In [8]:
data = data.drop(drop_dt, axis=1)

In [9]:
data.head(5)

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_length,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,10+ years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,10+ years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,10+ years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,10+ years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,3 years,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# List of columns to drop immediately due to high null rates or irrelevance
drop_dt = ['member_id', 'url', 'desc', 'emp_title', 'zip_code', 'title']
data.drop(drop_dt, axis=1, inplace=True)

# Advanced Filtering: Remove joint applications, hardship, and settlement data
# These are secondary attributes that do not affect the primary BI Star Schema
a = [x for x in data.columns if x.startswith('sec_app_') or x.endswith('_joint')]
b = [x for x in data.columns if x.startswith('settlement_') or x.startswith('hardship_')]
c = [x for x in data.columns if x.endswith('_inv')]

data.drop(a + b + c, axis=1, inplace=True, errors='ignore')

# Final selection of 30 core features for the BI model
# Purpose: Focus on Loan amount, Interest rate, Grade, and Repayment status
data.drop(['sub_grade', 'pymnt_plan', 'policy_code', 'initial_list_status', 
           'disbursement_method', 'deferral_term', 'acc_now_delinq', 'delinq_amnt',
           'orig_projected_additional_accrued_interest', 'mo_sin_old_il_acct', 
           'num_tl_120dpd_2m', 'funded_amnt', 'last_fico_range_high', 
           'last_fico_range_low', 'next_pymnt_d', 'last_credit_pull_d', 
           'total_rec_late_fee', 'collection_recovery_fee', 'payment_plan_start_date',
           'debt_settlement_flag', 'debt_settlement_flag_date', 'application_type'
          ], axis=1, inplace=True, errors='ignore')

Index(['id', 'loan_amnt', 'term', 'int_rate', 'installment', 'grade',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'purpose', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'fico_range_low', 'fico_range_high',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'out_prncp', 'total_pymnt', 'total_rec_prncp', 'total_rec_int',
       'recoveries', 'last_pymnt_d', 'last_pymnt_amnt',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_act_il',
       'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il',
       'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'mo_sin_old_rev_tl_op',
       'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc',
       'mths_since_recent_bc', 'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_30dpd',
       'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
       'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens',
       'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit'],
      dtype='object')

In [11]:
drop_patterns = [
    'open_', 'num_', 'mo_', 'mths_', 'inq_', 'bc_', 'pct_', 'percent_',
    'total_rec', 'total_bal', 'total_rev', 'total_cu', 'total_il', 'tot_'
]

specific_drops = [
    'funded_amnt', 'installment', 'verification_status', 
    'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d', 
    'last_fico_range_high', 'last_fico_range_low', 
    'collections_12_mths_ex_med', 'application_type', 
    'chargeoff_within_12_mths', 'delinq_amnt', 
    'pub_rec_bankruptcies', 'tax_liens', 
    'payment_plan_start_date', 'debt_settlement_flag', 
    'debt_settlement_flag_date', 'deferral_term',
    'orig_projected_additional_accrued_interest', 'disbursement_method',
    'acc_now_delinq', 'acc_open_past_24mths', 'avg_cur_bal'
]

cols = [c for c in data.columns if any(c.startswith(p) for p in drop_patterns) or c in specific_drops]

data.drop(columns=cols, inplace=True, errors='ignore')

In [23]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 2260639 entries, 0 to 2260698
Data columns (total 30 columns):
 #   Column            Dtype
---  ------            -----
 0   id                object
 1   loan_amnt         float64
 2   term              object
 3   int_rate          float64
 4   grade             object
 5   emp_length        object
 6   home_ownership    object
 7   annual_inc        float64
 8   issue_d           object
 9   loan_status       object
 10  purpose           object
 11  addr_state        object
 12  dti               float64
 13  delinq_2yrs       float64
 14  earliest_cr_line  object
 15  fico_range_low    float64
 16  fico_range_high   float64
 17  pub_rec           float64
 18  revol_bal         float64
 19  revol_util        float64
 20  total_acc         float64
 21  out_prncp         float64
 22  total_pymnt       float64
 23  recoveries        float64
 24  last_pymnt_d      object
 25  il_util           float64
 26  max_bal_bc        float64
 27  all_util          float64
 28  mort_acc          float64
 29  total_bc_limit    float64
dtypes: float64(19), object(11)
memory usage: 534.7+ MB

In [13]:
print(data.head(6))

         id  loan_amnt        term  int_rate grade emp_length home_ownership  \
0  68407277     3600.0   36 months     13.99     C  10+ years       MORTGAGE
1  68355089    24700.0   36 months     11.99     C  10+ years       MORTGAGE
2  68341763    20000.0   60 months     10.78     B  10+ years       MORTGAGE
3  66310712    35000.0   60 months     14.85     C  10+ years       MORTGAGE
4  68476807    10400.0   60 months     22.45     F    3 years       MORTGAGE
5  68426831    11950.0   36 months     13.44     C    4 years           RENT

   annual_inc   issue_d loan_status  ... total_acc out_prncp   total_pymnt  \
0     55000.0  Dec-2015  Fully Paid  ...      13.0      0.00   4421.723917
1     65000.0  Dec-2015  Fully Paid  ...      38.0      0.00  25679.660000
2     63000.0  Dec-2015  Fully Paid  ...      18.0      0.00  22705.924294
3    110000.0  Dec-2015     Current  ...      17.0  15897.65  31464.010000
4    104433.0  Dec-2015  Fully Paid  ...      35.0      0.00  11740.500000
5     34000.0  Dec-2015  Fully Paid  ...       6.0      0.00  13708.948530

   recoveries last_pymnt_d  il_util  max_bal_bc  all_util  mort_acc  \
0         0.0     Jan-2019     36.0       722.0      34.0       1.0
1         0.0     Jun-2016     73.0      6472.0      29.0       4.0
2         0.0     Jun-2017     73.0      2081.0      65.0       5.0
3         0.0     Feb-2019     70.0      6987.0      45.0       1.0
4         0.0     Jul-2016     84.0      9702.0      78.0       6.0
5         0.0     May-2017     99.0      4522.0      76.0       0.0

   total_bc_limit
0          2400.0
1         79300.0
2          6200.0
3         62500.0
4         20300.0
5          9400.0

[6 rows x 30 columns]

In [ ]:
# Step 1: Fill logical zeros for financial recovery and payment metrics
fill_0 = ['delinq_2yrs', 'pub_rec', 'mort_acc', 'total_acc', 'recoveries', 'out_prncp', 'total_pymnt']
for col in fill_0:
    data[col] = data[col].fillna(0)

# Step 2: Handle categorical missing values (Employment length)
data['emp_length'] = data['emp_length'].fillna('< 1 year')

# Step 3: Median Imputation for numerical features
# Median is used instead of Mean to avoid outliers in banking data
fill_median_cols = ['dti', 'revol_util', 'il_util', 'all_util', 'max_bal_bc', 'total_bc_limit', 'revol_bal']
for col in fill_median_cols:
    data[col] = data[col].fillna(data[col].median())

# Step 4: Drop rows with missing critical attributes (Target variables)
critical_cols = ['annual_inc', 'loan_amnt', 'loan_status', 'issue_d', 'grade', 'int_rate']
data.dropna(subset=critical_cols + ['earliest_cr_line'], inplace=True)

# Step 5: Logical mapping for last payment date
data['last_pymnt_d'] = data['last_pymnt_d'].fillna(data['issue_d'])

In [16]:
data.head(5)

,id,loan_amnt,term,int_rate,grade,emp_length,home_ownership,annual_inc,issue_d,loan_status,...,total_acc,out_prncp,total_pymnt,recoveries,last_pymnt_d,il_util,max_bal_bc,all_util,mort_acc,total_bc_limit
0,68407277,3600.0,36 months,13.99,C,10+ years,MORTGAGE,55000.0,Dec-2015,Fully Paid,...,13.0,0.00,4421.723917,0.0,Jan-2019,36.0,722.0,34.0,1.0,2400.0
1,68355089,24700.0,36 months,11.99,C,10+ years,MORTGAGE,65000.0,Dec-2015,Fully Paid,...,38.0,0.00,25679.660000,0.0,Jun-2016,73.0,6472.0,29.0,4.0,79300.0
2,68341763,20000.0,60 months,10.78,B,10+ years,MORTGAGE,63000.0,Dec-2015,Fully Paid,...,18.0,0.00,22705.924294,0.0,Jun-2017,73.0,2081.0,65.0,5.0,6200.0
3,66310712,35000.0,60 months,14.85,C,10+ years,MORTGAGE,110000.0,Dec-2015,Current,...,17.0,15897.65,31464.010000,0.0,Feb-2019,70.0,6987.0,45.0,1.0,62500.0
4,68476807,10400.0,60 months,22.45,F,3 years,MORTGAGE,104433.0,Dec-2015,Fully Paid,...,35.0,0.00,11740.500000,0.0,Jul-2016,84.0,9702.0,78.0,6.0,20300.0

In [17]:
data.isnull().any()

id                  False
loan_amnt           False
term                False
int_rate            False
grade               False
emp_length          False
home_ownership      False
annual_inc          False
issue_d             False
loan_status         False
purpose             False
addr_state          False
dti                 False
delinq_2yrs         False
earliest_cr_line    False
fico_range_low      False
fico_range_high     False
pub_rec             False
revol_bal           False
revol_util          False
total_acc           False
out_prncp           False
total_pymnt         False
recoveries          False
last_pymnt_d        False
il_util             False
max_bal_bc          False
all_util            False
mort_acc            False
total_bc_limit      False
dtype: bool

In [ ]:
# Final dataset shape check (Expecting ~2.26M rows and 30 columns)
print(f"Final Data Shape: {data.shape}")

# Export for SQL Server Staging (Chương 3)
# Note: This file will be ignored by Git to save space
data.to_csv('data_hqtcsdl.csv', index=False)

NameError: name 'data' is not defined

In [22]:
data.shape

(2260639, 30)

In [1]:
data.columns()

NameError: name 'data' is not defined